package Exception;

public class NestedDemo {

	public static void main(String[] args) {
		//  Begin Lab 4

		 // WHAT YOU NEED to do:  change this code to throw ArithmeticException

		
		//main try-block
        try{
            //try-block2
            try{
                //try-block3
                try{
                    int arr[]= {1,2,3,4};
    /* trying to display the value of an element which doesn't exist. The code should throw an exception       */
                    System.out.println(arr[10]);
                }catch(ArithmeticException e){
                    System.out.print("Arithmetic Exception");
                    System.out.println(" handled in try-block3");
                }
            }           catch(ArithmeticException e){
                System.out.print("Arithmetic Exception");
                System.out.println(" handled in try-block2");
            }
        }
        catch(ArithmeticException e3){
            System.out.print("Arithmetic Exception");
            System.out.println(" handled in main try-block");
        }
     
        
    
	}

}
